import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const RARETES = [
  { stars: 1, statMin: 0, statMax: 5, dropRate: 40 },
  { stars: 2, statMin: 3, statMax: 10, dropRate: 30 },
  { stars: 3, statMin: 8, statMax: 15, dropRate: 20 },
  { stars: 4, statMin: 13, statMax: 20, dropRate: 7 },
  { stars: 5, statMin: 18, statMax: 25, dropRate: 2.5 },
  { stars: 6, statMin: 23, statMax: 30, dropRate: 0.5 },
];

const MONSTRES = [
  {
    baseName: "Loup",
    tier: 1,
    name: "Loup I",
    vie: 10,
    force: 5,
    vitesse: 5,
    resistance: 6,
    agilite: 5,
    gainVictoire: 30,
    gainDefaite: 10,
  },
  {
    baseName: "Loup",
    tier: 2,
    name: "Loup II",
    vie: 60,
    force: 18,
    vitesse: 18,
    resistance: 9,
    agilite: 13,
    gainVictoire: 45,
    gainDefaite: 15,
  },
  {
    baseName: "Loup",
    tier: 3,
    name: "Loup III",
    vie: 85,
    force: 25,
    vitesse: 22,
    resistance: 13,
    agilite: 17,
    gainVictoire: 65,
    gainDefaite: 20,
  },
  {
    baseName: "Loup",
    tier: 4,
    name: "Loup IV",
    vie: 115,
    force: 33,
    vitesse: 27,
    resistance: 18,
    agilite: 22,
    gainVictoire: 90,
    gainDefaite: 28,
  },
  {
    baseName: "Loup",
    tier: 5,
    name: "Loup V",
    vie: 150,
    force: 42,
    vitesse: 33,
    resistance: 24,
    agilite: 28,
    gainVictoire: 120,
    gainDefaite: 36,
  },

  {
    baseName: "Ours",
    tier: 1,
    name: "Ours I",
    vie: 70,
    force: 18,
    vitesse: 6,
    resistance: 14,
    agilite: 4,
    gainVictoire: 30,
    gainDefaite: 10,
  },
  {
    baseName: "Ours",
    tier: 2,
    name: "Ours II",
    vie: 95,
    force: 25,
    vitesse: 8,
    resistance: 19,
    agilite: 6,
    gainVictoire: 45,
    gainDefaite: 15,
  },
  {
    baseName: "Ours",
    tier: 3,
    name: "Ours III",
    vie: 125,
    force: 33,
    vitesse: 10,
    resistance: 25,
    agilite: 8,
    gainVictoire: 65,
    gainDefaite: 20,
  },
  {
    baseName: "Ours",
    tier: 4,
    name: "Ours IV",
    vie: 160,
    force: 42,
    vitesse: 13,
    resistance: 32,
    agilite: 11,
    gainVictoire: 90,
    gainDefaite: 28,
  },
  {
    baseName: "Ours",
    tier: 5,
    name: "Ours V",
    vie: 200,
    force: 52,
    vitesse: 16,
    resistance: 40,
    agilite: 14,
    gainVictoire: 120,
    gainDefaite: 36,
  },

  // Slime : tanky, peu offensif, mais donne nettement plus d'XP que Loup/Ours
  {
    baseName: "Slime",
    tier: 1,
    name: "Slime I",
    vie: 40,
    force: 4,
    vitesse: 6,
    resistance: 8,
    agilite: 4,
    gainVictoire: 25,
    gainDefaite: 8,
    xpGain: 40,
  },
  {
    baseName: "Slime",
    tier: 2,
    name: "Slime II",
    vie: 90,
    force: 10,
    vitesse: 10,
    resistance: 14,
    agilite: 8,
    gainVictoire: 38,
    gainDefaite: 12,
    xpGain: 50,
  },
  {
    baseName: "Slime",
    tier: 3,
    name: "Slime III",
    vie: 140,
    force: 16,
    vitesse: 14,
    resistance: 20,
    agilite: 12,
    gainVictoire: 55,
    gainDefaite: 17,
    xpGain: 65,
  },
  {
    baseName: "Slime",
    tier: 4,
    name: "Slime IV",
    vie: 190,
    force: 22,
    vitesse: 18,
    resistance: 27,
    agilite: 16,
    gainVictoire: 75,
    gainDefaite: 23,
    xpGain: 80,
  },
  {
    baseName: "Slime",
    tier: 5,
    name: "Slime V",
    vie: 250,
    force: 30,
    vitesse: 22,
    resistance: 35,
    agilite: 20,
    gainVictoire: 100,
    gainDefaite: 30,
    xpGain: 100,
  },

  // Élémentaire : généraliste équilibré, seule source d'essence élémentaire
  {
    baseName: "Élémentaire",
    tier: 1,
    name: "Élémentaire I",
    vie: 55,
    force: 12,
    vitesse: 12,
    resistance: 10,
    agilite: 10,
    gainVictoire: 30,
    gainDefaite: 10,
  },
  {
    baseName: "Élémentaire",
    tier: 2,
    name: "Élémentaire II",
    vie: 80,
    force: 20,
    vitesse: 16,
    resistance: 15,
    agilite: 14,
    gainVictoire: 45,
    gainDefaite: 15,
  },
  {
    baseName: "Élémentaire",
    tier: 3,
    name: "Élémentaire III",
    vie: 110,
    force: 28,
    vitesse: 20,
    resistance: 21,
    agilite: 18,
    gainVictoire: 65,
    gainDefaite: 20,
  },
  {
    baseName: "Élémentaire",
    tier: 4,
    name: "Élémentaire IV",
    vie: 145,
    force: 36,
    vitesse: 25,
    resistance: 28,
    agilite: 23,
    gainVictoire: 90,
    gainDefaite: 28,
  },
  {
    baseName: "Élémentaire",
    tier: 5,
    name: "Élémentaire V",
    vie: 185,
    force: 46,
    vitesse: 30,
    resistance: 36,
    agilite: 28,
    gainVictoire: 120,
    gainDefaite: 36,
  },

  // Griffon : rapide et agile, seule source de plumes (bottes)
  {
    baseName: "Griffon",
    tier: 1,
    name: "Griffon I",
    vie: 60,
    force: 16,
    vitesse: 20,
    resistance: 8,
    agilite: 18,
    gainVictoire: 35,
    gainDefaite: 12,
  },
  {
    baseName: "Griffon",
    tier: 2,
    name: "Griffon II",
    vie: 100,
    force: 26,
    vitesse: 28,
    resistance: 13,
    agilite: 24,
    gainVictoire: 50,
    gainDefaite: 16,
  },
  {
    baseName: "Griffon",
    tier: 3,
    name: "Griffon III",
    vie: 140,
    force: 36,
    vitesse: 34,
    resistance: 19,
    agilite: 30,
    gainVictoire: 70,
    gainDefaite: 22,
  },
  {
    baseName: "Griffon",
    tier: 4,
    name: "Griffon IV",
    vie: 185,
    force: 46,
    vitesse: 40,
    resistance: 25,
    agilite: 36,
    gainVictoire: 95,
    gainDefaite: 30,
  },
  {
    baseName: "Griffon",
    tier: 5,
    name: "Griffon V",
    vie: 230,
    force: 58,
    vitesse: 46,
    resistance: 32,
    agilite: 42,
    gainVictoire: 125,
    gainDefaite: 38,
  },

  // Serpent de Cristal : très résistant, seule source d'écailles (amulettes)
  {
    baseName: "Serpent de Cristal",
    tier: 1,
    name: "Serpent de Cristal I",
    vie: 65,
    force: 14,
    vitesse: 10,
    resistance: 20,
    agilite: 8,
    gainVictoire: 35,
    gainDefaite: 12,
  },
  {
    baseName: "Serpent de Cristal",
    tier: 2,
    name: "Serpent de Cristal II",
    vie: 105,
    force: 22,
    vitesse: 14,
    resistance: 30,
    agilite: 12,
    gainVictoire: 50,
    gainDefaite: 16,
  },
  {
    baseName: "Serpent de Cristal",
    tier: 3,
    name: "Serpent de Cristal III",
    vie: 150,
    force: 30,
    vitesse: 18,
    resistance: 42,
    agilite: 16,
    gainVictoire: 70,
    gainDefaite: 22,
  },
  {
    baseName: "Serpent de Cristal",
    tier: 4,
    name: "Serpent de Cristal IV",
    vie: 195,
    force: 40,
    vitesse: 22,
    resistance: 55,
    agilite: 20,
    gainVictoire: 95,
    gainDefaite: 30,
  },
  {
    baseName: "Serpent de Cristal",
    tier: 5,
    name: "Serpent de Cristal V",
    vie: 245,
    force: 52,
    vitesse: 26,
    resistance: 68,
    agilite: 24,
    gainVictoire: 125,
    gainDefaite: 38,
  },
];

async function main() {
  for (const rarete of RARETES) {
    await prisma.rarity.upsert({
      where: { stars: rarete.stars },
      update: rarete,
      create: rarete,
    });
  }

  for (const monstre of MONSTRES) {
    await prisma.monster.upsert({
      where: {
        baseName_tier: { baseName: monstre.baseName, tier: monstre.tier },
      },
      update: monstre,
      create: monstre,
    });
  }

  console.log("Raretés et monstres créés.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
