-- AlterTable
ALTER TABLE "User" ADD COLUMN     "coupons" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "couponsUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "energy" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "energyUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
